config/routes.rb
TraineeApp::Application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
      resources :students do
       member do
        put 'assign_courses'
        put 'update_status'
        get 'send_mail'
       end
      end
      resources :studentids
      resources :colleges
      resources :courses
  root :to => 'welcome#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
	#atte_accessible :student_id ,:name,:image_filename,:remote_image_url
	#belongs_to :students
	#1 to many Model relationship
	belongs_to :college, :foreign_key => 'college_id'#1 to many Model relationship
	 #1 to 1 Model relationship
	 belongs_to :studentid
	
	has_many :courses_students
    has_many :courses, :through => :courses_students#many to many model relationships

	mount_uploader :image_filename, ImageUploader
	validates_presence_of :name 
		validates :phone,   :presence => {:message => 'hello world, bad operation!'},
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }
	validates_numericality_of :age
	validates_presence_of :address
	validates  :email , :presence => true ,
	:length => {:minimum => 3,:maximum => 254},
	:format => {:with => /\A^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$\z/i}
	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 before_action :authenticate_user!
  def index
    @students = Student.all
  end
  
  def new
  	@student = Student.new
    @studentids = Studentid.all
    
  end

  def create
    @student = Student.new(student_params)
    @studentids = Studentid.all
    puts "<<<<<<<<<<<<<<<<<<<student_params<<<<<<<<<<<"
    puts params[:student].inspect
    if @student.save
    	 redirect_to students_path
       
    else
    	 render :action => "new"
    end
  end
 
  def edit

    @student = Student.find(params[:id])
    @studentids = Studentid.all
  end 
  def update 
    @student = Student.find(params[:id])
    @studentids = Studentid.all
      if @student.update_attributes(student_params)
          redirect_to student_path(@student.id)
        else
          render :action => "edit"
        end
    end
  def show
    @student = Student.find(params[:id])
    @courses = Course.all                                                                                                                                                                                                                                                                                                      
  end

  def destroy
    @student = Student.find(params[:id])
    if @student.delete
       redirect_to students_path
    end
  end

def assign_courses
    @student=Student.find(params[:id])
    puts "<<<<<<<<<<<<params[:course_ids]<<<<<<<<<<<<<"
    puts params[:course_ids].inspect
    if !params[:course_ids].empty?
        params[:course_ids].each do |course_id|
        @courses_student = CoursesStudent.new(:student_id => @student.id,:course_id => course_id)
        @courses_student.save
    end
    else
      flash[:error]="error"
    end
      redirect_to students_path
end

def send_mail
 @student = Student.find(params[:id])
 if StudentMailer.new_student(@student).deliver
      message = "<span style='color: green'>Mail Sent</span>"
    else
      message = "<span style='color: red'>Error</span>"
    end
    render :text => message
end
def update_status
    @student = Student.find(params[:id])
    puts "<<<<<<<<<<<<javscrit<<<<<<<<<<<<<"

    if @student and @student.update_attributes(:status => params[:status])
      message = "<span style='color: green'>Updated</span>"
    else
      message = "<span style='color: red'>Error</span>"
    end
    render :text => message
  end

  private

  def student_params
    params.require(:student).permit(:image_filename,:name, :age, :address, :phone, :email ,:gender,:college_id,:studentid_id ,:status)
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="table-responsive">
	
 <%= form_for @student ,:html => {:multipart => true} do |f| %>
<table class="table" >
 
  	<tr>
			<td>Name:</td>
			<td>
				<%= f.text_field :name %>
				<%= validation_errors @student.errors['name'] %>
			</td>
	</tr>
	<tr>
			<td>Phone:</td>
			<td>
				<%= f.text_field :phone, :maxlength => 10%>
				<%= validation_errors @student.errors['phone'] %>
			</td>
	</tr>
	<tr>
			<td>Student_Id:</td>
			<td>
            <% @id_cards = [] %>
            <% @all_ids = Studentid.all %>
            <% @all_ids.each do |idcard| %>
             <% if idcard.student.nil? %>
               <% @id_cards << idcard %>
             <% end %>
            <% end %>
				<%= f.select :studentid_id, options_for_select([["Select Id cards",""]]+@id_cards.collect {|r| [r['idcards'],r['id']] },@student.studentid_id) %>

			</td>
	</tr> 
	<tr>
			<td>Age:</td>
			<td>
				<%= f.select :age ,options_for_select((1..100),@student.age),:prompt => "Select Age"%>
				<%= validation_errors @student.errors['age'] %>
			</td>
	</tr>
	<tr>
			<td>Address:</td>
			<td>
				<%= f.text_area :address %>
				<%= validation_errors @student.errors['address'] %>
			</td>
	</tr>
	 <tr>
			<td>Email:</td>
			<td>
				<%= f.text_field  (:email) %>
				<%= validation_errors @student.errors['email'] %>
			</td>
	</tr> 
	<tr>
			<td>Gender:</td>
			<td>
				 
			 	Male: <%= f.radio_button :gender, 'male' %>
			  	
			 	Female : <%= f.radio_button :gender, 'female'%>
				 
			</td>
	</tr>	
	<tr>	
	<td>
        <label  for="exampleInputFile">Photo </label>
        <%= f.file_field :image_filename,:onchange =>"validateFiles(this);",
          :data => {
          :max_file_size => 500.kilobytes
        }, :id => "exampleInputFile"%>
      
      </td>
      </tr>
      <tr>
	
		<td>
        	 College:
		</td>
	
		<td>
			<%= f.select :college_id, options_for_select((College.all(:select => "colname, id").map {|r| [r.colname,r.id] }), @student.college_id ),:prompt => "Select College" %>

				 
		</td>
	</tr>
	 <tr>
	
		<td>
        	  	<%= f.submit "Save" %>
		</td>
	
		<td>
				<%= link_to "Cancel",students_path %>
		</td>
	</tr>
</table>
<% end %>
  <script type="text/javascript">
    function validateFiles(inputFile) {
      var maxExceededMessage = "This file exceeds the maximum allowed file size (500 KB)";
      var extErrorMessage = "Only image file with extension: .jpg, .jpeg, .gif or .png is allowed";
      var allowedExtension = ["jpg", "jpeg", "gif", "png"];

      var extName;
      var maxFileSize = $(inputFile).data('max-file-size');
      var sizeExceeded = false;
      var extError = false;

      $.each(inputFile.files, function() {
        if (this.size && maxFileSize && this.size > parseInt(maxFileSize)) {sizeExceeded=true;};
        extName = this.name.split('.').pop();
        if ($.inArray(extName, allowedExtension) == -1) {extError=true;};
      });
      if (sizeExceeded) {
        window.alert(maxExceededMessage);
        $(inputFile).val('');
      };

      if (extError) {
        window.alert(extErrorMessage);
        $(inputFile).val('');
      };
    }
  </script>
</div>

app/views/students/edit.html.erb
<h2>Edit Student List</h2>
<%= render "form" %> 

app/views/students/index.html.erb
<div class="table-responsive">
<h2>Students List </h2>
<span><%= link_to "Create New Student Here",new_student_path,:style => "float :right" %>
</span>
  <table class="table">
     <th>Student Name</th>
     <th>Email</th>
     <th>Status</th>
      <th>Options</th>	
       
          <% if @students.empty? %>
            
                <tr class="active">
                <td class="active"> No Students Found </td>
                  </tr>
            <% else %>
            
             <% @students.each do |student| %>
            
               <tr class="active">
            
                  <td class="active"> 
   	              <%=link_to student.name,student_path(student.id), :style => "text-decoration:none; font_weight:bold; color:green;" %>
                  </td>
            
                  <td class="active"> 
   	              <%= student.email %>
                  </td>
                  <td>
                    <div id="status_<%= student.id %>"></div>
                     <%= select_tag :status, options_for_select([['Select Status', ''],['Active', 'Active'], ['Inactive', 'Inactive']],  student.status), :onchange => "update_guest_status(this.value, '#{ student.id }')"  %>
                   </td>

                  <td class="active"> 
   	              <%= link_to "Edit",edit_student_path(student.id) %> |
                  <%= link_to "delete",student_path(student.id), :method => :delete, :confirm => "Are you sure to delete this student ?" %> |
                    <div id="email_<%= student.id %>"></div>
                    <%= submit_tag ("Mail"),:onclick => "send_student_mail('#{ student.email }','#{ student.id }')"%>
                  </td>
                </tr>

               <% end %>
            <% end %>
	</table>
</div> 

app/views/students/new.html.erb
<h2>Create Student List</h2>
<%= render "form" %> 

app/views/students/show.html.erb
<div class="table-responsive">

<h2>List Of Students </h2> 
<table class="table">
	<tr>
		<td>Name:</td>
		<td><%= @student.name %></td>	
	</tr>	
	<tr>
		<td>Age:</td>
		<td><%= @student.age %></td>	
	</tr>	
	<tr>
		<td>Address:</td>
		<td><%= @student.address %></td>	
	</tr>	
	<tr>	
		<td>Email:</td>	
		<td><%= @student.email %></td>
	</tr>
	<tr>
		<td>Phone:</td>
		<td><%= @student.phone %></td>	
	</tr>	
	<tr>
		<td>Gender:</td>
		<td><%= @student.gender %></td>
	</tr>
	<tr>
		<td>ID card Detail:</td>
		<td><%= @student.studentid.idcards %></td>
	</tr>
	<table width="100%" border="1%">
		<tr>
			<td>
				<%= form_tag assign_courses_student_path(@student.id), :method => :put do %>
                 <% @courses.each do |course|%>
                  <%= check_box_tag "course_ids[]",course.id,CoursesStudent.exists?(:student_id => @student.id,  :course_id => course.id)  ? true : false %>
                  <%=  course.cname %>
                 <% end %>
                 <%=submit_tag "assign"%>
                <% end %>
			</td>
		</tr>

	</table>
			
	<tr>
		<td>Image:</td>
		<td><%= image_tag @student.image_filename %></td>
	</tr>
	<tr>
		<td><%= link_to "Home Page", students_path %></td>	
	</tr>
</table>
</div>